#!/bin/bash

clock() {
    printf '%s\n' "$(date +"%H:%M %p ")"
}

music() {
    song_air=$(mpc status | grep -m1 "" | tr -d " ")

    if mpc status | grep -q '\[playing\]';
    then
        printf '%s\n' "$song_air"
    else
        printf '%s\n' "꧁ღff-airღ꧂"
    fi
}
weather(){
    #showforecast=$(awk 'NR==1' "$HOME/.local/share/forecast_report")
    showforecast=$(grep -m1 "" "$HOME/.local/share/forecast_report")
    printf '%s\n' "$showforecast"
}

volume() {
    NOTMUTED=$(amixer -c 1 -M | head -5 | grep "\[on\]")
    AUDIO=$(amixer -c 1 -M | head -5 | grep -o -m 1 -E "[[:digit:]]+%")

    if [ -z "$NOTMUTED" ];
    then
        echo "🔇 muted "
    else
        case "$AUDIO" in
            0%|[0-9]%) echo "🔊 $AUDIO " ;;
            1?%|2?%|3?%) echo "🔊 $AUDIO " ;;
            4?%|5?%|6?%) echo "🔊 $AUDIO " ;;
            *) echo "🔊 $AUDIO " ;;
        esac
    fi
}

while true;
do
    xsetroot -name "$(clock)• $(music) • $(weather) • $(volume)"
    sleep 1m;
done &
