#!/usr/bin/env sh

# Feed script a url or file location.
# If an image, it will view in sxiv,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.
#BROWSER='tsurf'
videoQue=/tmp/mpvinput
# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
    *mkv|*webm|*mp4|*erome.com/*|*bitchute.com/*|*twitter.com/* \
        |*hooktube.com*|*youtube.com/*|*youtu.be/*|*invidio.us/*)
           setsid pueue add -- mpv --input-file="${videoQue}" "${1}" \
                > /dev/null 2>&1 & ;;
#            [ ! -p "$videoQue" ] && mkfifo "$videoQue"
#            if pgrep -f "${videoQue}" > /dev/null; then
#                printf "%s\n" "loadfile \"${1}\" append-play" > $videoQue
#            else
            #setsid mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet "$1" >/dev/null 2>&1 & ;;
    *.png|*.jpg|*.jpe|*.jpeg|*.gif|*gfycat.com/*)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" \
            && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
    *mp3|*flac|*opus|*mp3?source*)
        setsid tsp curl -LO "$1" >/dev/null 2>&1 & ;;
    magnet:*|*.torrent)
        transadd "$1" ;;
    *reddit.com/*)
        st -e rtv -l "$1" >/dev/null 2>&1 & ;;
    *)
        if [ -f "$1" ]; then "$TERMINAL" -e "$EDITOR $1"
        else setsid "$BROWSER" "$1" >/dev/null 2>&1 & fi ;;
esac
exit 0
