#!/usr/bin/env sh

url=$(xsel -ob)

#case "$url" in
#    http*) tsp mpv \
#        --ontop --no-border \
#        --force-window \
#        --autofit=500x280 \
#        --geometry=-15-53 \
#        "${url}" ;;
#      *)
#          ;;
#esac
[ -z "$url" ] && { "$BROWSER"; exit; }

case "$url" in
	*mkv|*webm|*mp4|*m3u8|*youtube.com/*|*playlist*\
        |*youtu.be/*|*hooktube.com*|*watch*|*video*|*sendvid*\
        |*bitchute.com*|*bilibili.com/*|*animeone.me*\
        |*ixigua.com/*)
		setsid pueue add -- mpv --input-ipc-server=/tmp/mpvsoc$(date +%s) -quiet \
            "$url" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$url" > "/tmp/$(echo "$url" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$url" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source*)
		setsid tsp curl -LO "$url" >/dev/null 2>&1 & ;;
	*)
		if [ -f "$url" ]; then "$TERMINAL" -e "$EDITOR $url"
		else setsid $BROWSER "$url" >/dev/null 2>&1 & fi ;;
esac
exit 0
