#!/usr/bin/env bash

DEFAULT="$BROWSERCLI"
VIDEO_QUEUE="tsp mpv"
VIDEO_CLIP="mpv --loop --quiet"
IMAGECLI="sxiveh"
TORRENTCLI="transmission-remote --add"
LIVEFEED="you-get -p mpv"
DDL_PATH=~/Downloads/plowshare
DDL_QUEUE_FAST=~/.config/plowshare/queuefast.txt

# enable case-insensitive matching
shopt -s nocasematch

url="$1"
case "$url" in
    *gfycat.com/*|*streamable.com/*)
        nohup $VIDEO_CLIP "${url/.gifv/.webm}" > /dev/null 2>&1 & ;;
    *v.redd.it/*|*video.twimg.com/*|*dailymotion.com*)
        nohup $VIDEO_CLIP "$url" > /dev/null 2>&1 &
        ;;
    *youtube.com/watch*|*youtu.be/*|*clips.twitch.tv/*|*twitter.com/*)
        $VIDEO_QUEUE "$(echo "$url" | sed -e "s/youtube.com/invidio.us/g")"
        >/dev/null 2>&1 &
        ;;
    *twitch.tv/*)
        $LIVEFEED "$url"
        ;;
    *reddit.com/r/*)
        st -e rtv -l "$url" &
        ;;
    *i.imgur.com/*.gifv|*i.imgur.com/*.mp4|*i.imgur.com/*.webm|*i.imgur.com/*.gif)
        nohup "$VIDEO_CLIP" "$url" > /dev/null 2>&1&
        ;;
    *i.imgur.com/*| *imgur.com/*.*)
        nohup $VIDEO_CLIP "$url"
        ;;
    *imgur.com/*)
        imgWrapper "$url" >/dev/null 2>&1 &
        ;;
    *.pls|*.m3u)
        mpv "$url"
        ;;
    magnet:*|*.torrent)
        $TORRENTCLI "$url"
        ;;
    *.jpg|*.jpeg|*.png|*:large)
        # nohup $IMAGEGUI "$url" > /dev/null 2>&1 &
        $IMAGECLI "$url" >/dev/null 2>&1 &
        ;;
    *.gif)
        nohup $VIDEO_CLIP "${url/.gifv/.webm}" > /dev/null 2>&1 &
        ;;
    *zippyshare.com/*|*mediafire.com/file/*|*sendspace.com/file/*)
        if pgrep -f $DDL_QUEUE_FAST > /dev/null
        then
            echo "$url" >> $DDL_QUEUE_FAST
        else
            echo "$url" >> $DDL_QUEUE_FAST
            cat $DDL_QUEUE_FAST | awk '!x[$0]++' | sponge $DDL_QUEUE_FAST
            tmux split-window -fv -p 20 && tmux send-keys "until [[ \$(cat $DDL_QUEUE_FAST | grep -v '#' | wc -l) -eq 0 ]]; do mkdir -p $DDL_PATH && cd $DDL_PATH && plowdown -m $DDL_QUEUE_FAST -o $DDL_PATH ; done" 'Enter'
        fi
        ;;
    *.m3u8|*.mp4|*.mkv|*.avi|*.wmv|*.m4v|*.mpg|*.mpeg|*.flv|*.ogm|*.ogv|*.gifv)
        $VIDEO_QUEUE "$url"
        ;;
    *.mp3|*.m4a|*.wav|*.ogg|*.oga|*.flac)
        # create queue fifo files if it does not exist
        if [[ ! -p /tmp/mpvinput ]]; then
            mkfifo /tmp/mpvinput
        fi

        # check if process mpv exist (e.g mpv --input-file=/tmp/mpvinput filename.mp3)
        if pgrep -f mpvinput > /dev/null
        then
            # if mpv is already running then append new url/files to queue
            # echo loadfile \"${url/'/\\'}\" append-play > /tmp/mpvinput
            echo loadfile \"$url\" append-play > /tmp/mpvinput
        # nohup $VIDEO_CLIP "${url/.gifv/.webm}" > /dev/null 2>&1 &
        else
            # if mpv is not running then start it (initial startup)
            # mpv --no-video --input-file=/tmp/mpvinput "$1"
            tmux split-window -fv -p 20 && tmux send-keys "mpv --no-video --input-file=/tmp/mpvinput \"$url\" && exit" 'Enter'
        fi
        # Note: use "<" or ">" hotkeys to skip between songs/audio queue list on mpv
        ;;
    *)
        # $DEFAULT "$url"
        tmux new-window -n browse && tmux send-keys "$DEFAULT '$url' && tmux kill-pane" 'Enter'
        ;;
esac

